name: RedirectDuplicatePosts CI

on:
  push:

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        exclude-files: '.deployignore'
        exclude-directories: '.github,assets'

    - name: Checkout to Master Built branch
      if: github.ref == 'refs/heads/master'
      env:
        USER_EMAIL: "badasswpdev@gmail.com"
        USER_NAME: "badasswp"
      run: |
        git config user.email "${USER_EMAIL}"
        git config user.name "${USER_NAME}"
        git checkout -b master-built

    - name: Clean Up Files
      run: |
        while IFS= read -r file; do
          git rm -rf "$file"
        done < .deployignore
        git rm .deployignore

    - name: Push to Master Built
      run: |
        git commit -m "push to master-built"
        git push origin master-built -f
        rm -rf .git